### PR TITLE
docs: add usage information to example readmes and fix typos

### PR DESCRIPTION
**Pull request by jhiga**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/4)

### CODE REVIEW

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/4)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @jhiga)

___
*[examples/run-stcv-2instances/README.md, line 43 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/4#-MUCMPKP6BqlqaqWXky4:-MUCMPKP6BqlqaqWXky5:bt06j6s) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/5fa267d3d25ebf42eb8fac3fae49ccfc4c68175d/examples/run-stcv-2instances/README.md#L43)):*
> ```Markdown
> | Name |
> |------|
> | [azurerm_subnet](https://registry.terraform.io/providers/hashicorp/azurerm/>=2.37.0/docs/data-sources/subnet) |
> ```

Was this manually added?   This is in the TERRAFORM DOCS hook so it could get replaced.

**Review by jhiga — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/4)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @rmyers808)

___
*[examples/run-stcv-2instances/README.md, line 43 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/4#-MUCMPKP6BqlqaqWXky4:-MUC_zgRB2Fo5xDBaY1m:bj1463m) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-stcv/blob/5fa267d3d25ebf42eb8fac3fae49ccfc4c68175d/examples/run-stcv-2instances/README.md#L43)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Was this manually added?   This is in the TERRAFORM DOCS hook so it could get replaced.
</blockquote></details>

This was added by running `pre-commit run -a`

**Review by rmyers808 — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/4)* status: 2 of 3 files reviewed, all discussions resolved

**Review by rmyers808 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-stcv/4#-:-MUEFHYM5no7C60tqG8X:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved

**Pull request merged**
